version: '3'

volumes:
  local_mongodb_data: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: csv_analyzer_production_django
    links:
      - mongodb
    depends_on:
      - postgres
      - redis
      - mongodb
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: csv_analyzer_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: csv_analyzer_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: csv_analyzer_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: csv_analyzer_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: csv_analyzer_production_flower
    command: /start-flower

  
  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
#      - local_mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: django_mongodb_docker
    ports:
      - 27017:27017
